const DEBUG = false;

const C = {
	SCREEN_WIDTH: 700,
	SCREEN_HEIGHT: 700,
	PLAYER_BASE_SPEED: 13,
	PLAYER_MAX_SPEED: 400,
	WORLD_SCROLL_SPEED: 150,
	PLAYER_BULLET_BASE_SPEED: 700,
	PLAYER_DRAG: 300
};

